CREATE SCHEMA inventory;

GRANT ALL ON SCHEMA inventory TO app_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA inventory
    GRANT ALL ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA inventory
    GRANT ALL ON SEQUENCES TO app_user;
